# SPDX-License-Identifier: Apache-2.0
"""Projection-only v2 arena and asynchronous slot ownership; no device imports."""

from dataclasses import asdict

from tools.qwen4exp.streaming_memory import CAPACITIES, Region
from tools.qwen4exp.streaming_protocol import canonical_sha256

ABI_VERSION = 2
M, N, GROUP, K0, BLOCK, LANES = 32, 160, 128, 64, 16, 8
MAX_K, MAX_GROUPS, SLOTS, METADATA_SLOTS, BLOCKS = 2560, 20, 2, 3, 8
ALIGNMENT, CONTROL_EVENT = 32, 3


def regions():
    """No live aliases; output is transient metadata staging before row execution."""
    specs = (
        ("packed_activation", "UB", SLOTS * M * GROUP, "int4", "[slot,limb,kblock,M,32]"),
        ("raw_product", "UB", SLOTS * 2 * M * N * 4, "int32", "[slot,N16,2*M,16]"),
        ("float_product", "UB", SLOTS * 2 * M * N * 4, "float32", "[slot,N16,2*M,16]"),
        ("accumulator", "UB", M * N * 4, "float32", "[N16,M,16]"),
        ("weight_metadata", "UB", 3 * N * MAX_GROUPS * 4, "float32", "[bank,N16,groups,16]"),
        ("activation_metadata", "UB", METADATA_SLOTS * 2 * M * LANES * 4, "float32", "[slot,bank,M,8]"),
        ("projected_output", "UB", M * N * 2, "float16", "[N16,M,16] or prepare-only FP16 metadata bank"),
        ("ends", "UB", 32 * 8, "int64", "[32]"),
        ("route_ids", "UB", 128 * 4, "int32", "reserved control rows"),
        ("activation_l1", "L1", SLOTS * M * GROUP, "int4", "[slot,limb,kblock,M,32]"),
        ("resident_weight", "L1", N * MAX_K // 2, "int4", "[N16,group,kblock,16,32]"),
        ("activation_l0", "L0A", SLOTS * M * GROUP, "int4", "[slot,limb,M16,kblock,16,32]"),
        ("weight_l0", "L0B", SLOTS * N * GROUP // 2, "int4", "[slot,kblock,N16,16,32]"),
        ("cube_product", "L0C", 2 * M * N * 4, "int32", "[N16,2*M,16]"),
    )
    offsets = dict.fromkeys(dict(CAPACITIES), 0)
    result = []
    for name, space, size, dtype, layout in specs:
        offset = (offsets[space] + ALIGNMENT - 1) // ALIGNMENT * ALIGNMENT
        result.append(Region(name, space, offset, size, dtype, layout, "exclusive until consumer/event release"))
        offsets[space] = offset + size
    if any(offsets[space] > capacity for space, capacity in CAPACITIES):
        raise ValueError("projection v2 arena overcommit")
    if N * MAX_GROUPS * 2 > M * N * 2:
        raise ValueError("transient FP16 metadata bank does not fit projected output arena")
    return tuple(result)


def contract():
    values = {
        name: value
        for name, value in (
            ("M", M),
            ("N", N),
            ("GROUP", GROUP),
            ("K0", K0),
            ("BLOCK", BLOCK),
            ("LANES", LANES),
            ("MAX_K", MAX_K),
            ("MAX_GROUPS", MAX_GROUPS),
            ("SLOTS", SLOTS),
            ("METADATA_SLOTS", METADATA_SLOTS),
            ("BLOCKS", BLOCKS),
            ("ALIGNMENT", ALIGNMENT),
            ("CONTROL_EVENT", CONTROL_EVENT),
        )
    }
    body = dict(
        abi_version=ABI_VERSION,
        constants=values,
        regions=[asdict(r) for r in regions()],
        scope="standalone projection; reference WY; no runtime admission",
        hardware_validated=False,
    )
    return dict(body, contract_sha256=canonical_sha256(body))


def render_header():
    c = contract()
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by streaming_next_memory.py; unqualified v2 candidate.",
        "#ifndef QWEN_STREAMING_NEXT_CONTRACT_H",
        "#define QWEN_STREAMING_NEXT_CONTRACT_H",
        "#include <stdint.h>",
        "namespace qwen_streaming_next {",
        f'constexpr const char* CONTRACT_SHA256 = "{c["contract_sha256"]}";',
        f"constexpr uint32_t ABI_VERSION = {ABI_VERSION};",
    ]
    values = dict(c["constants"])
    for r in regions():
        values[r.name.upper() + "_OFFSET"] = r.offset
        values[r.name.upper() + "_BYTES"] = r.nbytes
        if r.name in (
            "packed_activation",
            "raw_product",
            "float_product",
            "activation_l1",
            "activation_l0",
            "weight_l0",
        ):
            values[r.name.upper() + "_SLOT_BYTES"] = r.nbytes // SLOTS
        if r.name == "activation_metadata":
            values["ACTIVATION_METADATA_SLOT_BYTES"] = r.nbytes // METADATA_SLOTS
    for name, value in values.items():
        lines.append(f"constexpr uint32_t {name} = {value};")
    for space, limit in CAPACITIES:
        used = max(r.end for r in regions() if r.space == space)
        lines += [
            f"constexpr uint32_t {space}_USED = {used};",
            f"constexpr uint32_t {space}_LIMIT = {limit};",
            f'static_assert({space}_USED <= {space}_LIMIT, "{space} overcommit");',
        ]
    lines += [
        "__aicore__ constexpr uint32_t EventId(uint32_t slot) { return slot; }",
        "__aicore__ constexpr uint32_t Slot(uint32_t group) { return group % SLOTS; }",
        "__aicore__ constexpr uint32_t MetadataSlot(uint32_t group) { return group % METADATA_SLOTS; }",
        "}  // namespace qwen_streaming_next",
        "#endif",
    ]
    return "\n".join(lines) + "\n"
